spring.application.name=PlayMySongs
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=playMySong
# limite padrao do spring e 1MB, pequeno para mp3
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
